services:
  - type: web
    name: ete-resource-backend
    runtime: node
    buildCommand: cd my-backend && npm install
    startCommand: cd my-backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
